POST http://localhost:8080/api/chirps HTTP/1.1
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "da5bddf9-73d5-46bc-b4f0-2b9637d8a661"
}

###
POST http://localhost:8080/api/chirps HTTP/1.1
Content-Type: application/json

{
  "body": "I once told a woman I was Kevin Costner, and it worked because I believed it.",
  "user_id": "da5bddf9-73d5-46bc-b4f0-2b9637d8a661"
}

###
GET http://localhost:8080/api/chirps HTTP/1.1
Content-Type: application/json